### ISSUE TITLE
who are you

### ISSUE THREAD

**Issue by tjsongzw** [narumiruna/narumiruna#1]
👤 是谁 😆

**Comment by narumiruna** [comment]
我啊

**Comment by tjsongzw** [comment]
Dogikorize?

**Comment by narumiruna** [comment]
你猜這是誰
![image](https://user-images.githubusercontent.com/4680567/87010384-11ed4000-c1f9-11ea-8847-09ea720b70de.png)

**Comment by tjsongzw** [comment]
哈哈哈哈!!!
怎么搞得, 用了什么GAN吗?

**Comment by narumiruna** [comment]
FaceApp
